bundler_args: --without development production --quiet
env:
  - GEM=backend DB=mysql
  - GEM=backend DB=postgres
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - cd $GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"
script:
  - bundle exec rake test_app
  - bundle exec rspec -f d spec/features/admin/orders/order_details_spec.rb
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
